site_name: mkdocs-pdf-export-plugin
theme:
  name: readthedoscs
use_directory_urls: false
plugins:
  - search
  - pdf-export:
      combined: true
      pandoc_template: template.latex

nav:
  - Intro: index.md
  - Options: options.md